services:
  laravel.test:
    build:
      context: ./vendor/laravel/sail/runtimes/8.3
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      WWWGROUP: "${WWWGROUP:-1000}"
      WWWUSER: "1337"
      NODE_VERSION: "20"
      YARN_VERSION: "1.22.19"
      LARAVEL_SAIL: 1
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
  mysql:
    image: 'mysql:8.0'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 't4f_assignment'
    volumes:
      - 'sailmysql:/var/lib/mysql'
    networks:
      - sail
networks:
  sail:
    driver: bridge
volumes:
  sailmysql:
    driver: local
